[project]
name = "europa-clipper-ccsds-plugin"
version = "0.1.0"
description = "CCSDS packet definitions for Europa Clipper instruments"
authors = [
    {name = "Joshua Garde",email = "jgarde@jpl.nasa.gov"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "ccsdspy~=1.3.0"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "ccsds" }
]

[dependency-groups]
dev = [
    "pytest (>=8.0.0,<9.0.0)",
    "spac-kit>=0,<1",
    "flake8>=6.0.0,<7.0.0",
    "pylint>=3.0.0,<4.0.0",
    "numpy (<2)"
]
