[project]
name = "europa-clipper-ccsds-plugin"
version = "0.1.0"
description = "CCSDS packet definitions for Europa Clipper instruments"
authors = [
    {name = "Joshua Garde",email = "jgarde@jpl.nasa.gov"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydownlinkparser>=0,<1"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "ccsds" }
]
